name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
        architecture: x64

    - name: Build Dependencies (Linux)
      run: sudo apt-get update && sudo apt-get install -y bison flex

    - name: Fetch Dependencies
      run: gradle --init-script gradle/support/fetchDependencies.gradle init

    - name: Build with Gradle
      run: gradle buildGhidra

    - uses: actions/upload-artifact@v2
      with:
        name: Linux-Release
        path: build/dist/ghidra_*_linux64.zip
